### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by hglaude** [shiranD/specializer#6]
Hello,

Thank you for your contribution. In order to be used by other people, I would appreciate if you could add a LICENSE file. Without it, your code is not open source.

Please see: https://help.github.com/articles/licensing-a-repository/

Thanks,
Hadrien

**Comment by MarkAtwood** [comment]
Since OpenFST itself is licensed under Apache-2.0, it would make sense for this project to have the same license.

**Comment by shiranD** [comment]
Thanks for informing me of that!
I added the Apache license :-)
